OnlineShop/urls.py
from django.conf.urls import url, include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('shop.urls', namespace='shop')),
    url(r'^account/', include('account.urls')),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static
urlpatterns = [
    url(r'^$', views.dashboard, name='index'),
    url(r'^list/$', views.product_list, name='product_list'),
    url(r'^(?P<category_slug>[-\w]+)/$',
        views.product_list,
        name='product_list_by_category'),
    url(r'^(?P<id>\d+)/(?P<slug>[-\w]+)/$',
        views.product_detail,
        name='product_detail'),
]
if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

shop/models.py
from django.db import models
from django.core.urlresolvers import reverse
from django.contrib.auth.models import User
from taggit.managers import TaggableManager
"""
git init
git add .
git commit -m "修改了index"
git remote add origin https://github.com/luoying1105/zhufang.git
git push -u origin master

"""


# 类型
class Category(models.Model):  # 种类
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    def get_absolute_url(self):
        return reverse('shop:product_list_by_category',
                       args=[self.slug])

    class Meta:
        ordering = ('name',)
        verbose_name = 'category'
        verbose_name_plural = 'categories'

    def __str__(self):
        return self.name


# 装修类型
class ApartmentLayout(models.Model):
    name = models.CharField('装修质量', max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'layout'
        verbose_name_plural = 'Layouts'

    def __str__(self):
        return self.name
        # 3室2厅1卫 整租69㎡ 向南 高层/共16层 精装修 普通住宅


# 设备
class Device(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'device'
        verbose_name_plural = 'devices'

    def __str__(self):
        return self.name


# 校区
class Campus(models.Model):
    name = models.CharField(max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)
    img = models.ImageField()
    description = models.CharField(max_length=300,default='宇宙中心五道口附近，方便出行、购物，适合陪读、考研、校外住宿。')

    class Meta:
        ordering = ('name',)
        verbose_name = 'cumpus'
        verbose_name_plural = 'cumpies'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:campus_list',
                       args=[self.id, self.slug])


# 小区 路段
class Updown(models.Model):
    name = models.CharField('小区名称', max_length=200,
                            db_index=True)
    address = models.CharField('详细地址', max_length=300,
                               db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = ''
        verbose_name_plural = 'cities'

    def __str__(self):
        return '{}小区{}'.format(self.name, self.address)

    def get_absolute_url(self):
        return reverse('shop:dashboard_for_updown',
                       args=[self.id, self.slug])

#户型
class Layout(models.Model):
    bedroom_count = models.IntegerField(default=1)
    bashroom_count = models.IntegerField(default=1)
    livingroom_count = models.IntegerField(default=0)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    def __str__(self):
        return '{}室{}厅{}卫'.format(str(self.bedroom_count),str(self.livingroom_count),str(self.bashroom_count))
# 行政区域
class Administrative_division(models.Model):
    name = models.CharField('行政区域', max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)
    def __str__(self):
        return self.name


# 城市
class City(models.Model):
    name = models.CharField('城市', max_length=200,
                            db_index=True)
    slug = models.SlugField(max_length=200,
                            db_index=True,
                            unique=True)

    class Meta:
        ordering = ('name',)
        verbose_name = 'city'
        verbose_name_plural = 'cities'

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('shop:dashboard_for_city',
                       args=[self.slug])


class Product(models.Model):
    # 多对一
    category = models.ForeignKey(Category, related_name='products')
    # 装修质量
    apartment_layout = models.ForeignKey(ApartmentLayout, related_name='apartment')
    #户型
    layout = models.ForeignKey(Layout,related_name="huxing")
    # 设施 多对多
    device = models.ManyToManyField(Device, related_name='device')
    # city
    locate = models.ForeignKey(City, related_name='city_locate')
    # 校区
    campus = models.ManyToManyField(Campus, related_name='campus_locate')
    distance = models.CharField('与校区距离', max_length=200, db_index=True)
    locations = models.ForeignKey(Administrative_division, related_name='lactional')
    updown = models.ForeignKey(Updown, related_name='updown_locate')
    #发布账户
    author = models.ForeignKey(User,
                               related_name='product_posts')

    name = models.CharField('商品名', max_length=200, db_index=True)
    slug = models.SlugField('链接地址', max_length=200, db_index=True)
    image = models.ImageField('商品图像', upload_to='products/%Y/%m/%d', blank=True)
    orientations = models.CharField('房间朝向', max_length=20, default='朝南')
    height = models.IntegerField('房间层高', default=0)
    description = models.TextField('描述', blank=True)
    price = models.DecimalField('价格', max_digits=10, decimal_places=2)  # 小数位数
    stock = models.PositiveIntegerField('库存', )
    available = models.BooleanField('是否上架', default=True)
    created = models.DateTimeField('创建时间', auto_now_add=True)
    updated = models.DateTimeField('发布时间', auto_now=True)
    tags = TaggableManager()#标签

    def get_absolute_url(self):
        return reverse('shop:product_detail',
                       args=[self.id, self.slug])

    class Meta:
        ordering = ('name',)
        index_together = (('id', 'slug'),)

    def __str__(self):
        return self.name

shop/forms.py
# -*- coding: UTF-8 -*-
from django import forms
from django.utils.translation import ugettext_lazy as _
from .models import *

shop/views.py
from django.shortcuts import render, get_object_or_404
from .models import *
from django.contrib.auth import authenticate, login
from django.contrib.auth.decorators import login_required


@login_required
def product_list(request, category_slug=None,):
    category = None
    categories = Category.objects.all()
    # 获取所有校区
    campus = Campus.objects.all()
    compus = None
    apartment_layout = ApartmentLayout.objects.all()
    device = Device.objects.all()
    products = Product.objects.filter(available=True)  # 拿取已经上架的全部商品

    if category_slug:  # 我们将使用一个可选的category_slug参数可选的过滤产品给定的类别。
        category = get_object_or_404(Category, slug=category_slug)
        products = products.filter(category=category)

    return render(request,
                  'shop/product/list.html',
                  {'category': category,
                   'categories': categories,
                   'apartment_layout': apartment_layout,
                   'device': device,
                   'campus': campus,
                   'compus': compus,
                   'products': products})


@login_required
def dashboard(request, city_slug=None):
    city = City.objects.all()[:5]  # 只选前五个
    products = Product.objects.filter(available=True)[:3]  # 拿取3个已经上架的全部商品
    campus = Campus.objects.all()[:3]
    if city_slug:  # 我们将使用一个可选的category_slug参数可选的过滤产品给定的类别。
        city = get_object_or_404(City, slug=city_slug)
        products = products.filter(city_name=city)
    return render(request,
                  'shop/product/index.html',
                  {'section': 'dashboard',
                   'cities': city,
                   'products': products,
                   'campus': campus
                   })


# 就是商品的详细信息页面
def product_detail(request, id, slug):
    product = get_object_or_404(Product, id=id, slug=slug, available=True)
    return render(request,
                  'shop/detail.html',
                  {'product': product})

templates/shop/product/detail.html
{% extends "shop/base.html" %}
{% load static %}
{% block title %}
    {% if category %}{{ category.title }}{% else %}Products{% endif %}
{% endblock %}
{% block content %}
    <div class="product-detail">
        <img src="{% if product.image %}{{ product.image.url }}{% else %}
{% static "img/no_image.png" %}{% endif %}">
        <h1>{{ product.name }}</h1>
        <h2><a href="{{ product.category.get_absolute_url }}">{{ product.category }}</a></h2>
        <p class="price">${{ product.price }}</p>
        {{ product.description|linebreaks }}
    </div>
{% endblock %}

templates/shop/product/list.html
{% extends "base.html" %}
{% load static %}
{% block title %}
    list
{% endblock %}

{% block content %}
    <div id="navbar-top" class="navbar-top navbar navbar-default navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <img src="/static/image/logo.png"><a href="/" class="navbar-brand" style="height: 10px">校园租</a>
                <!--<img src="/assets/img/bl.png">-->
            </div>
            <p class="navbar-text navbar-right co-brand hidden-xs"><img src="/static/image/logo.png"></p>

            <ul class="nav navbar-nav navbar-right">
                {% if request.user.is_authenticated %}

                    <li class="dropdown">
                        <a href="#" class="dropdown-toggle" data-toggle="dropdown">您好 {{ request.user }} <span
                                class="caret"></span></a>
                        <ul class="dropdown-menu" role="menu">
                            <li><a href="#">Action</a></li>
                            <li><a href="#">Another action</a></li>
                            <li><a href="#">Something else here</a></li>
                            <li class="divider"></li>
                            <li><a href="#">Separated link</a></li>
                        </ul>
                    </li>
                    <li><a href="{% url "logout" %}">注销</a></li>
                {% else %}
                    <li><a href="{% url "login" %}">登录</a></li>
                    <li><a href="{% url "logout" %}">注册</a></li>{% endif %}
            </ul>
        </div>
    </div>
    <header id="top-header" class="top-header jumbotron"
            style="background-image: url('/static/image/banner_bg.png'); background-repeat: no-repeat;background-size: cover">
        <div class="container">
            <div class="row">
                <div class="col-md-8">
                    <div class="page-header">
                        <h1>租房网</h1>
                        <p class="lead">好房子都在这里啦！</p>
                    </div>
                    <div class="features media">
                        <p class="media-left">快捷入口：</p>
                        <div class="media-body">
                            <p class="coms">
                                <a target="_blank" href="#"
                                   class="label label-default label-ali">阿里</a>
                                <!-- <a href="/company/腾讯" class="label label-default label-tencent" onclick="_hmt.push(['_trackEvent', 'coms', 'click', '腾讯'])">腾讯</a> -->
                                <a target="_blank" href="#"
                                   class="label label-default label-baidu">百度</a>
                                <a target="_blank" href="http://company.liepin.com/3264402?mscid=b_o_0001"
                                   class="label label-default label-sina"
                                   onclick="_hmt.push(['_trackEvent', 'coms', 'click', '金山'])">金山</a>
                                <a target="_blank" href="http://company.liepin.com/856639?mscid=b_o_0001"
                                   class="label label-default label-sohu"
                                   onclick="_hmt.push(['_trackEvent', 'coms', 'click', '迅雷'])">迅雷</a>
                                <a target="_blank" href="http://company.liepin.com/6429309?mscid=b_o_0001"
                                   class="label label-default label-360"
                                   onclick="_hmt.push(['_trackEvent', 'coms', 'click', '360'])">360</a>
                                <!-- <a href="/company/小米" class="label label-default label-xiaomi" onclick="_hmt.push(['_trackEvent', 'coms', 'click', '小米'])">小米</a> -->
                                <a target="_blank" href="http://company.liepin.com/947003?mscid=b_o_0001"
                                   class="label label-default label-lenovo"
                                   onclick="_hmt.push(['_trackEvent', 'coms', 'click', '畅游'])">畅游</a>
                            </p>
                            <p class="salary">
                                <a href="/salary/10" class="label label-default"
                                   onclick="_hmt.push(['_trackEvent', 'salary', 'click', '10万起'])">10万起</a>
                                <a href="/salary/20" class="label label-default"
                                   onclick="_hmt.push(['_trackEvent', 'salary', 'click', '20万起'])">20万起</a>
                                <a href="/salary/30" class="label label-default"
                                   onclick="_hmt.push(['_trackEvent', 'salary', 'click', '30万起'])">30万起</a>
                                <a href="/salary/50" class="label label-default"
                                   onclick="_hmt.push(['_trackEvent', 'salary', 'click', '50万起'])">50万起</a>
                                <a href="/salary/土豪" class="label label-default"
                                   onclick="_hmt.push(['_trackEvent', 'salary', 'click', '土豪'])">土豪</a>
                            </p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </header>
    <div class="container">
        <div class="row">
            <div class="row">
                <div class="col-xs-6 col-md-3">
                    <div id="sidebar">
                        <h3>Categories</h3>
                        <ul class="nav nav-pills nav-stacked" role="tablist">
                            <li {% if not category %}class="selected"{% endif %}>
                                <a href="{% url "shop:product_list" %}">All</a>
                            </li>
                            {% for c in categories %}
                                <li {% if category.slug == c.slug %}class="selected"{% endif %}>
                                    <a href="{{ c.get_absolute_url }}">{{ c.name }}</a>
                                </li>
                            {% endfor %}
                        </ul>
                    </div>
                </div>
                <div class="col-xs-12 col-md-8">
                    <div id="main" class="product-list">
                        <h1>{% if category %}{{ category.name }}{% else %}Products{% endif %}</h1>
                        <div class="row">
                            {% for product in products %}
                                <div class="col-sm-6 col-md-4">

                                    <div class="thumbnail">
                                        <img src="{% if product.image %}{{ product.image.url }}{% else %}{% static 'img/no_image.png' %}{% endif %}">
                                        <div class="caption">
                                            <h3>{{ product.name|linebreaks|truncatechars:20 }}</h3>
                                            <h6> ${{ product.price }}</h6>
                                            <p>{{ product.description|truncatechars_html:30 }}</p>
                                            <p>
                                                <a href="{{ product.get_absolute_url }}" class="btn btn-primary"
                                                   role="button">详细信息</a>
                                                <a href="#" role="button">Button</a>
                                            </p>
                                        </div>
                                    </div>
                                </div>{% endfor %}

                        </div>
                    </div>
                    <div class="row">
                        <div class="col-xs-6 col-sm-4">.col-xs-6 .col-sm-4</div>
                        <div class="col-xs-6 col-sm-4">.col-xs-6 .col-sm-4</div>
                        <!-- Optional: clear the XS cols if their content doesn't match in height -->
                        <div class="clearfix visible-xs-block"></div>
                        <div class="col-xs-6 col-sm-4">.col-xs-6 .col-sm-4</div>
                    </div>

                </div>
            </div>
        </div>
    </div>




{% endblock %}